version: '3.1'
services:
  mongo:
    image: "mongo:3.6"
    ports:
     - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: test_database
    expose:
     - "27017"
  rabbitmq:
    image: rabbitmq:3.7-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
